### ISSUE TITLE
Programmatically create JSON for Administrative Units

### ISSUE THREAD

**Issue by danhorst** [ndlib/locabulary#5]
I would like to be able to rebuild a JSON file of Administrative Units from the working list maintained in [a google sheet](https://docs.google.com/spreadsheets/d/1oBW5FCTtYXsUi8roBiMRBLFY3dXamhTqy-kiG2rqu5Q/edit?usp=sharing).

Use a gem to fetch the data. There are [several options](https://www.ruby-toolbox.com/search?utf8=%E2%9C%93&q=google+drive). The [google_drive gem](https://rubygems.org/gems/google_drive) looks promising ([project repo](https://github.com/gimite/google-drive-ruby)).

Put the script to do this in an appropriate place `/bin`, `/script`, etc.

**Comment by rbalekai** [comment]
https://github.com/ndlib/locabulary/pull/11

**Comment by jeremyf** [comment]
This is done, but needs revisions.
